# Generated by Django 5.2 on 2026-03-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пацієнта', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Користувача', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
