# Generated by Django 5.0.6 on 2026-03-05 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва спеціальності')),
                ('icon', models.CharField(default='🏥', max_length=50, verbose_name='Іконка (emoji або Bootstrap Icons клас)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Досвід роботи (років)')),
                ('description', models.TextField(blank=True, verbose_name='Опис / про лікаря')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Приймає пацієнтів')),
                ('slot_duration', models.PositiveIntegerField(default=30, verbose_name='Тривалість прийому (хв)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialty', verbose_name='Спеціальність')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('work_start', models.TimeField(verbose_name='Початок роботи')),
                ('work_end', models.TimeField(verbose_name='Кінець роботи')),
                ('is_working', models.BooleanField(default=True, verbose_name='Робочий день')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='Лікар')),
            ],
            options={
                'verbose_name': 'Розклад лікаря',
                'verbose_name_plural': 'Розклади лікарів',
                'ordering': ['day_of_week'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
