# Generated by Django 5.2 on 2026-03-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Лікаря', 'verbose_name_plural': 'Лікарі'},
        ),
    ]
