# Generated by Django 5.0.6 on 2026-03-05 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата та час прийому')),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='planned', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки пацієнта при записі')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='Лікар')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patient', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Запис на прийом',
                'verbose_name_plural': 'Записи на прийом',
                'ordering': ['-date_time'],
                'unique_together': {('doctor', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Діагноз')),
                ('treatment', models.TextField(verbose_name='Призначення / лікування')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='Приватні нотатки лікаря')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заповнення')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment', verbose_name='Запис на прийом')),
            ],
            options={
                'verbose_name': 'Медична картка',
                'verbose_name_plural': 'Медичні картки',
                'ordering': ['-created_at'],
            },
        ),
    ]
