# Generated by Django 5.2 on 2026-03-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Медичну картку', 'verbose_name_plural': 'Медичні картки'},
        ),
    ]
