# Generated by Django 5.2 on 2026-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patient_options_alter_user_options'),
        ('appointments', '0002_alter_medicalrecord_options'),
        ('doctors', '0002_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'date_time'), name='unique_active_appointment'),
        ),
    ]
