# Generated by Django 5.2 on 2026-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_unique_together_add_partial_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина звернення'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('planned', 'Заплановано'),
                    ('completed', 'Завершено'),
                    ('cancelled', 'Скасовано'),
                    ('missed', 'Пропущено'),
                ],
                default='planned',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(
                condition=~models.Q(status__in=['cancelled', 'missed']),
                fields=('doctor', 'date_time'),
                name='unique_active_appointment',
            ),
        ),
    ]
